---
title: 'Tidy Tuesday #3'
author: "Erik Hager"
output: 
  html_document:
    df_print: paged
    code_download: true
    theme: journal
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error=TRUE, message=FALSE, warning=FALSE)
```

```{r libraries}
library(tidyverse)     
library(lubridate)     
library(ggthemes)      
```

```{r}
members <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-22/members.csv')
expeditions <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-22/expeditions.csv')
peaks <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-22/peaks.csv')
```

**Question:** How have deaths varied over the years at these six popular climbing peaks?

```{r}
memex <- members %>% 
  inner_join(expeditions, by = "expedition_id") %>% 
  select(expedition_id, 
         member_id,
         year.x,
         season.x,
         peak_name.x,
         sex,
         age,
         died)

memex

memex %>% 
  filter(died %in% c("TRUE")) %>%
  filter(peak_name.x %in% c("Everest",
                            "Kangchenjunga", 
                            "Manaslu",
                            "Dhaulagiri I", 
                            "Ama Dablam", 
                            "Annapurna I")) %>%
  group_by(peak_name.x, year.x) %>% 
  summarize(deaths = sum(died)) %>%
  ggplot(aes(x = year.x, y = deaths, color= peak_name.x)) +
  geom_line() +
  labs(title = "Climbing Deaths Over Time at Various Peaks",
       y = "Deaths",
       x = "Year",
       color = "Peak") +
  theme_dark()
```










































